// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alert_dispatches.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAlertDispatch = `-- name: CreateAlertDispatch :one
INSERT INTO alert_dispatches (id, spray_report_id, beekeeper_id, apiary_id, distance_m, downwind, call_state, sms_state, ledger_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, spray_report_id, beekeeper_id, apiary_id, distance_m, downwind, push_state, push_at, call_state, call_at, call_attempts, sms_state, sms_at, in_app_confirmed_at, in_app_action, final_status, twilio_call_sid, twilio_sms_sid, ledger_hash, created_at
`

type CreateAlertDispatchParams struct {
	ID            uuid.UUID `json:"id"`
	SprayReportID uuid.UUID `json:"spray_report_id"`
	BeekeeperID   uuid.UUID `json:"beekeeper_id"`
	ApiaryID      uuid.UUID `json:"apiary_id"`
	DistanceM     float64   `json:"distance_m"`
	Downwind      bool      `json:"downwind"`
	CallState     CallState `json:"call_state"`
	SmsState      SmsState  `json:"sms_state"`
	LedgerHash    string    `json:"ledger_hash"`
}

func (q *Queries) CreateAlertDispatch(ctx context.Context, arg CreateAlertDispatchParams) (AlertDispatch, error) {
	row := q.db.QueryRowContext(ctx, createAlertDispatch,
		arg.ID,
		arg.SprayReportID,
		arg.BeekeeperID,
		arg.ApiaryID,
		arg.DistanceM,
		arg.Downwind,
		arg.CallState,
		arg.SmsState,
		arg.LedgerHash,
	)
	var i AlertDispatch
	err := row.Scan(
		&i.ID,
		&i.SprayReportID,
		&i.BeekeeperID,
		&i.ApiaryID,
		&i.DistanceM,
		&i.Downwind,
		&i.PushState,
		&i.PushAt,
		&i.CallState,
		&i.CallAt,
		&i.CallAttempts,
		&i.SmsState,
		&i.SmsAt,
		&i.InAppConfirmedAt,
		&i.InAppAction,
		&i.FinalStatus,
		&i.TwilioCallSid,
		&i.TwilioSmsSid,
		&i.LedgerHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAlertDispatch = `-- name: GetAlertDispatch :one
SELECT id, spray_report_id, beekeeper_id, apiary_id, distance_m, downwind, push_state, push_at, call_state, call_at, call_attempts, sms_state, sms_at, in_app_confirmed_at, in_app_action, final_status, twilio_call_sid, twilio_sms_sid, ledger_hash, created_at FROM alert_dispatches WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAlertDispatch(ctx context.Context, id uuid.UUID) (AlertDispatch, error) {
	row := q.db.QueryRowContext(ctx, getAlertDispatch, id)
	var i AlertDispatch
	err := row.Scan(
		&i.ID,
		&i.SprayReportID,
		&i.BeekeeperID,
		&i.ApiaryID,
		&i.DistanceM,
		&i.Downwind,
		&i.PushState,
		&i.PushAt,
		&i.CallState,
		&i.CallAt,
		&i.CallAttempts,
		&i.SmsState,
		&i.SmsAt,
		&i.InAppConfirmedAt,
		&i.InAppAction,
		&i.FinalStatus,
		&i.TwilioCallSid,
		&i.TwilioSmsSid,
		&i.LedgerHash,
		&i.CreatedAt,
	)
	return i, err
}

const getDispatchByTwilioCallSID = `-- name: GetDispatchByTwilioCallSID :one
SELECT id, spray_report_id, beekeeper_id, apiary_id, distance_m, downwind, push_state, push_at, call_state, call_at, call_attempts, sms_state, sms_at, in_app_confirmed_at, in_app_action, final_status, twilio_call_sid, twilio_sms_sid, ledger_hash, created_at FROM alert_dispatches WHERE twilio_call_sid = $1 LIMIT 1
`

func (q *Queries) GetDispatchByTwilioCallSID(ctx context.Context, twilioCallSid sql.NullString) (AlertDispatch, error) {
	row := q.db.QueryRowContext(ctx, getDispatchByTwilioCallSID, twilioCallSid)
	var i AlertDispatch
	err := row.Scan(
		&i.ID,
		&i.SprayReportID,
		&i.BeekeeperID,
		&i.ApiaryID,
		&i.DistanceM,
		&i.Downwind,
		&i.PushState,
		&i.PushAt,
		&i.CallState,
		&i.CallAt,
		&i.CallAttempts,
		&i.SmsState,
		&i.SmsAt,
		&i.InAppConfirmedAt,
		&i.InAppAction,
		&i.FinalStatus,
		&i.TwilioCallSid,
		&i.TwilioSmsSid,
		&i.LedgerHash,
		&i.CreatedAt,
	)
	return i, err
}

const getDispatchByTwilioSMSSID = `-- name: GetDispatchByTwilioSMSSID :one
SELECT id, spray_report_id, beekeeper_id, apiary_id, distance_m, downwind, push_state, push_at, call_state, call_at, call_attempts, sms_state, sms_at, in_app_confirmed_at, in_app_action, final_status, twilio_call_sid, twilio_sms_sid, ledger_hash, created_at FROM alert_dispatches WHERE twilio_sms_sid = $1 LIMIT 1
`

func (q *Queries) GetDispatchByTwilioSMSSID(ctx context.Context, twilioSmsSid sql.NullString) (AlertDispatch, error) {
	row := q.db.QueryRowContext(ctx, getDispatchByTwilioSMSSID, twilioSmsSid)
	var i AlertDispatch
	err := row.Scan(
		&i.ID,
		&i.SprayReportID,
		&i.BeekeeperID,
		&i.ApiaryID,
		&i.DistanceM,
		&i.Downwind,
		&i.PushState,
		&i.PushAt,
		&i.CallState,
		&i.CallAt,
		&i.CallAttempts,
		&i.SmsState,
		&i.SmsAt,
		&i.InAppConfirmedAt,
		&i.InAppAction,
		&i.FinalStatus,
		&i.TwilioCallSid,
		&i.TwilioSmsSid,
		&i.LedgerHash,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAlertsByBeekeeper = `-- name: ListActiveAlertsByBeekeeper :many
SELECT ad.id, ad.spray_report_id, ad.beekeeper_id, ad.apiary_id, ad.distance_m, ad.downwind, ad.push_state, ad.push_at, ad.call_state, ad.call_at, ad.call_attempts, ad.sms_state, ad.sms_at, ad.in_app_confirmed_at, ad.in_app_action, ad.final_status, ad.twilio_call_sid, ad.twilio_sms_sid, ad.ledger_hash, ad.created_at FROM alert_dispatches ad
WHERE ad.beekeeper_id = $1 AND ad.final_status IS NULL
ORDER BY ad.created_at DESC
`

func (q *Queries) ListActiveAlertsByBeekeeper(ctx context.Context, beekeeperID uuid.UUID) ([]AlertDispatch, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAlertsByBeekeeper, beekeeperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertDispatch{}
	for rows.Next() {
		var i AlertDispatch
		if err := rows.Scan(
			&i.ID,
			&i.SprayReportID,
			&i.BeekeeperID,
			&i.ApiaryID,
			&i.DistanceM,
			&i.Downwind,
			&i.PushState,
			&i.PushAt,
			&i.CallState,
			&i.CallAt,
			&i.CallAttempts,
			&i.SmsState,
			&i.SmsAt,
			&i.InAppConfirmedAt,
			&i.InAppAction,
			&i.FinalStatus,
			&i.TwilioCallSid,
			&i.TwilioSmsSid,
			&i.LedgerHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAlertsByBeekeeper = `-- name: ListAllAlertsByBeekeeper :many
SELECT id, spray_report_id, beekeeper_id, apiary_id, distance_m, downwind, push_state, push_at, call_state, call_at, call_attempts, sms_state, sms_at, in_app_confirmed_at, in_app_action, final_status, twilio_call_sid, twilio_sms_sid, ledger_hash, created_at FROM alert_dispatches WHERE beekeeper_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAllAlertsByBeekeeper(ctx context.Context, beekeeperID uuid.UUID) ([]AlertDispatch, error) {
	rows, err := q.db.QueryContext(ctx, listAllAlertsByBeekeeper, beekeeperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertDispatch{}
	for rows.Next() {
		var i AlertDispatch
		if err := rows.Scan(
			&i.ID,
			&i.SprayReportID,
			&i.BeekeeperID,
			&i.ApiaryID,
			&i.DistanceM,
			&i.Downwind,
			&i.PushState,
			&i.PushAt,
			&i.CallState,
			&i.CallAt,
			&i.CallAttempts,
			&i.SmsState,
			&i.SmsAt,
			&i.InAppConfirmedAt,
			&i.InAppAction,
			&i.FinalStatus,
			&i.TwilioCallSid,
			&i.TwilioSmsSid,
			&i.LedgerHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDispatchSiblings = `-- name: ListDispatchSiblings :many
SELECT id, spray_report_id, beekeeper_id, apiary_id, distance_m, downwind, push_state, push_at, call_state, call_at, call_attempts, sms_state, sms_at, in_app_confirmed_at, in_app_action, final_status, twilio_call_sid, twilio_sms_sid, ledger_hash, created_at FROM alert_dispatches
WHERE spray_report_id = $1 AND beekeeper_id = $2
ORDER BY distance_m ASC
`

type ListDispatchSiblingsParams struct {
	SprayReportID uuid.UUID `json:"spray_report_id"`
	BeekeeperID   uuid.UUID `json:"beekeeper_id"`
}

// All dispatches belonging to the same beekeeper for the same spray, ordered
// closest-apiary-first. Used to coalesce per-beekeeper notifications and to
// propagate confirmation state from the primary dispatch to siblings.
func (q *Queries) ListDispatchSiblings(ctx context.Context, arg ListDispatchSiblingsParams) ([]AlertDispatch, error) {
	rows, err := q.db.QueryContext(ctx, listDispatchSiblings, arg.SprayReportID, arg.BeekeeperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertDispatch{}
	for rows.Next() {
		var i AlertDispatch
		if err := rows.Scan(
			&i.ID,
			&i.SprayReportID,
			&i.BeekeeperID,
			&i.ApiaryID,
			&i.DistanceM,
			&i.Downwind,
			&i.PushState,
			&i.PushAt,
			&i.CallState,
			&i.CallAt,
			&i.CallAttempts,
			&i.SmsState,
			&i.SmsAt,
			&i.InAppConfirmedAt,
			&i.InAppAction,
			&i.FinalStatus,
			&i.TwilioCallSid,
			&i.TwilioSmsSid,
			&i.LedgerHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDispatchesBySpray = `-- name: ListDispatchesBySpray :many
SELECT id, spray_report_id, beekeeper_id, apiary_id, distance_m, downwind, push_state, push_at, call_state, call_at, call_attempts, sms_state, sms_at, in_app_confirmed_at, in_app_action, final_status, twilio_call_sid, twilio_sms_sid, ledger_hash, created_at FROM alert_dispatches WHERE spray_report_id = $1 ORDER BY created_at
`

func (q *Queries) ListDispatchesBySpray(ctx context.Context, sprayReportID uuid.UUID) ([]AlertDispatch, error) {
	rows, err := q.db.QueryContext(ctx, listDispatchesBySpray, sprayReportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertDispatch{}
	for rows.Next() {
		var i AlertDispatch
		if err := rows.Scan(
			&i.ID,
			&i.SprayReportID,
			&i.BeekeeperID,
			&i.ApiaryID,
			&i.DistanceM,
			&i.Downwind,
			&i.PushState,
			&i.PushAt,
			&i.CallState,
			&i.CallAt,
			&i.CallAttempts,
			&i.SmsState,
			&i.SmsAt,
			&i.InAppConfirmedAt,
			&i.InAppAction,
			&i.FinalStatus,
			&i.TwilioCallSid,
			&i.TwilioSmsSid,
			&i.LedgerHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInAppConfirmed = `-- name: SetInAppConfirmed :exec
UPDATE alert_dispatches
SET in_app_confirmed_at = NOW(), in_app_action = $2, final_status = $3
WHERE id = $1 AND final_status IS NULL
`

type SetInAppConfirmedParams struct {
	ID          uuid.UUID       `json:"id"`
	InAppAction NullInAppAction `json:"in_app_action"`
	FinalStatus NullFinalStatus `json:"final_status"`
}

func (q *Queries) SetInAppConfirmed(ctx context.Context, arg SetInAppConfirmedParams) error {
	_, err := q.db.ExecContext(ctx, setInAppConfirmed, arg.ID, arg.InAppAction, arg.FinalStatus)
	return err
}

const setTwilioCallSID = `-- name: SetTwilioCallSID :exec
UPDATE alert_dispatches SET twilio_call_sid = $2, call_state = 'queued', call_at = NOW() WHERE id = $1
`

type SetTwilioCallSIDParams struct {
	ID            uuid.UUID      `json:"id"`
	TwilioCallSid sql.NullString `json:"twilio_call_sid"`
}

func (q *Queries) SetTwilioCallSID(ctx context.Context, arg SetTwilioCallSIDParams) error {
	_, err := q.db.ExecContext(ctx, setTwilioCallSID, arg.ID, arg.TwilioCallSid)
	return err
}

const setTwilioSMSSID = `-- name: SetTwilioSMSSID :exec
UPDATE alert_dispatches SET twilio_sms_sid = $2, sms_state = 'queued', sms_at = NOW() WHERE id = $1
`

type SetTwilioSMSSIDParams struct {
	ID           uuid.UUID      `json:"id"`
	TwilioSmsSid sql.NullString `json:"twilio_sms_sid"`
}

func (q *Queries) SetTwilioSMSSID(ctx context.Context, arg SetTwilioSMSSIDParams) error {
	_, err := q.db.ExecContext(ctx, setTwilioSMSSID, arg.ID, arg.TwilioSmsSid)
	return err
}

const updateCallState = `-- name: UpdateCallState :exec
UPDATE alert_dispatches SET call_state = $2, call_at = NOW(), call_attempts = call_attempts + 1 WHERE id = $1
`

type UpdateCallStateParams struct {
	ID        uuid.UUID `json:"id"`
	CallState CallState `json:"call_state"`
}

func (q *Queries) UpdateCallState(ctx context.Context, arg UpdateCallStateParams) error {
	_, err := q.db.ExecContext(ctx, updateCallState, arg.ID, arg.CallState)
	return err
}

const updateCallStateByTwilioSID = `-- name: UpdateCallStateByTwilioSID :exec
UPDATE alert_dispatches SET call_state = $2, call_at = NOW() WHERE twilio_call_sid = $1
`

type UpdateCallStateByTwilioSIDParams struct {
	TwilioCallSid sql.NullString `json:"twilio_call_sid"`
	CallState     CallState      `json:"call_state"`
}

func (q *Queries) UpdateCallStateByTwilioSID(ctx context.Context, arg UpdateCallStateByTwilioSIDParams) error {
	_, err := q.db.ExecContext(ctx, updateCallStateByTwilioSID, arg.TwilioCallSid, arg.CallState)
	return err
}

const updateDispatchLedgerHash = `-- name: UpdateDispatchLedgerHash :exec
UPDATE alert_dispatches SET ledger_hash = $2 WHERE id = $1
`

type UpdateDispatchLedgerHashParams struct {
	ID         uuid.UUID `json:"id"`
	LedgerHash string    `json:"ledger_hash"`
}

func (q *Queries) UpdateDispatchLedgerHash(ctx context.Context, arg UpdateDispatchLedgerHashParams) error {
	_, err := q.db.ExecContext(ctx, updateDispatchLedgerHash, arg.ID, arg.LedgerHash)
	return err
}

const updateFinalStatus = `-- name: UpdateFinalStatus :exec
UPDATE alert_dispatches SET final_status = $2 WHERE id = $1 AND final_status IS NULL
`

type UpdateFinalStatusParams struct {
	ID          uuid.UUID       `json:"id"`
	FinalStatus NullFinalStatus `json:"final_status"`
}

func (q *Queries) UpdateFinalStatus(ctx context.Context, arg UpdateFinalStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFinalStatus, arg.ID, arg.FinalStatus)
	return err
}

const updateFinalStatusByCallSID = `-- name: UpdateFinalStatusByCallSID :exec
UPDATE alert_dispatches SET final_status = $2 WHERE twilio_call_sid = $1 AND final_status IS NULL
`

type UpdateFinalStatusByCallSIDParams struct {
	TwilioCallSid sql.NullString  `json:"twilio_call_sid"`
	FinalStatus   NullFinalStatus `json:"final_status"`
}

func (q *Queries) UpdateFinalStatusByCallSID(ctx context.Context, arg UpdateFinalStatusByCallSIDParams) error {
	_, err := q.db.ExecContext(ctx, updateFinalStatusByCallSID, arg.TwilioCallSid, arg.FinalStatus)
	return err
}

const updateFinalStatusBySMSSID = `-- name: UpdateFinalStatusBySMSSID :exec
UPDATE alert_dispatches SET final_status = $2 WHERE twilio_sms_sid = $1 AND final_status IS NULL
`

type UpdateFinalStatusBySMSSIDParams struct {
	TwilioSmsSid sql.NullString  `json:"twilio_sms_sid"`
	FinalStatus  NullFinalStatus `json:"final_status"`
}

func (q *Queries) UpdateFinalStatusBySMSSID(ctx context.Context, arg UpdateFinalStatusBySMSSIDParams) error {
	_, err := q.db.ExecContext(ctx, updateFinalStatusBySMSSID, arg.TwilioSmsSid, arg.FinalStatus)
	return err
}

const updatePushState = `-- name: UpdatePushState :exec
UPDATE alert_dispatches SET push_state = $2, push_at = NOW() WHERE id = $1
`

type UpdatePushStateParams struct {
	ID        uuid.UUID `json:"id"`
	PushState PushState `json:"push_state"`
}

func (q *Queries) UpdatePushState(ctx context.Context, arg UpdatePushStateParams) error {
	_, err := q.db.ExecContext(ctx, updatePushState, arg.ID, arg.PushState)
	return err
}

const updateSMSState = `-- name: UpdateSMSState :exec
UPDATE alert_dispatches SET sms_state = $2, sms_at = NOW() WHERE id = $1
`

type UpdateSMSStateParams struct {
	ID       uuid.UUID `json:"id"`
	SmsState SmsState  `json:"sms_state"`
}

func (q *Queries) UpdateSMSState(ctx context.Context, arg UpdateSMSStateParams) error {
	_, err := q.db.ExecContext(ctx, updateSMSState, arg.ID, arg.SmsState)
	return err
}

const updateSMSStateByTwilioSID = `-- name: UpdateSMSStateByTwilioSID :exec
UPDATE alert_dispatches SET sms_state = $2, sms_at = NOW() WHERE twilio_sms_sid = $1
`

type UpdateSMSStateByTwilioSIDParams struct {
	TwilioSmsSid sql.NullString `json:"twilio_sms_sid"`
	SmsState     SmsState       `json:"sms_state"`
}

func (q *Queries) UpdateSMSStateByTwilioSID(ctx context.Context, arg UpdateSMSStateByTwilioSIDParams) error {
	_, err := q.db.ExecContext(ctx, updateSMSStateByTwilioSID, arg.TwilioSmsSid, arg.SmsState)
	return err
}
