// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apiaries.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createApiary = `-- name: CreateApiary :one
INSERT INTO apiaries (id, owner_id, name, type, lat, lng, hive_count, start_date, end_date, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, owner_id, name, type, lat, lng, hive_count, start_date, end_date, notes, created_at, ledger_hash
`

type CreateApiaryParams struct {
	ID        uuid.UUID      `json:"id"`
	OwnerID   uuid.UUID      `json:"owner_id"`
	Name      string         `json:"name"`
	Type      ApiaryType     `json:"type"`
	Lat       float64        `json:"lat"`
	Lng       float64        `json:"lng"`
	HiveCount int32          `json:"hive_count"`
	StartDate time.Time      `json:"start_date"`
	EndDate   sql.NullTime   `json:"end_date"`
	Notes     sql.NullString `json:"notes"`
}

func (q *Queries) CreateApiary(ctx context.Context, arg CreateApiaryParams) (Apiary, error) {
	row := q.db.QueryRowContext(ctx, createApiary,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Type,
		arg.Lat,
		arg.Lng,
		arg.HiveCount,
		arg.StartDate,
		arg.EndDate,
		arg.Notes,
	)
	var i Apiary
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Type,
		&i.Lat,
		&i.Lng,
		&i.HiveCount,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.CreatedAt,
		&i.LedgerHash,
	)
	return i, err
}

const getApiary = `-- name: GetApiary :one
SELECT id, owner_id, name, type, lat, lng, hive_count, start_date, end_date, notes, created_at, ledger_hash FROM apiaries WHERE id = $1 LIMIT 1
`

func (q *Queries) GetApiary(ctx context.Context, id uuid.UUID) (Apiary, error) {
	row := q.db.QueryRowContext(ctx, getApiary, id)
	var i Apiary
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Type,
		&i.Lat,
		&i.Lng,
		&i.HiveCount,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.CreatedAt,
		&i.LedgerHash,
	)
	return i, err
}

const listAllApiaries = `-- name: ListAllApiaries :many
SELECT id, owner_id, name, type, lat, lng, hive_count, start_date, end_date, notes, created_at, ledger_hash FROM apiaries ORDER BY created_at DESC
`

func (q *Queries) ListAllApiaries(ctx context.Context) ([]Apiary, error) {
	rows, err := q.db.QueryContext(ctx, listAllApiaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Apiary{}
	for rows.Next() {
		var i Apiary
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Type,
			&i.Lat,
			&i.Lng,
			&i.HiveCount,
			&i.StartDate,
			&i.EndDate,
			&i.Notes,
			&i.CreatedAt,
			&i.LedgerHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiariesByOwner = `-- name: ListApiariesByOwner :many
SELECT id, owner_id, name, type, lat, lng, hive_count, start_date, end_date, notes, created_at, ledger_hash FROM apiaries WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListApiariesByOwner(ctx context.Context, ownerID uuid.UUID) ([]Apiary, error) {
	rows, err := q.db.QueryContext(ctx, listApiariesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Apiary{}
	for rows.Next() {
		var i Apiary
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Type,
			&i.Lat,
			&i.Lng,
			&i.HiveCount,
			&i.StartDate,
			&i.EndDate,
			&i.Notes,
			&i.CreatedAt,
			&i.LedgerHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApiary = `-- name: UpdateApiary :one
UPDATE apiaries
SET name = $2, type = $3, lat = $4, lng = $5, hive_count = $6,
    start_date = $7, end_date = $8, notes = $9
WHERE id = $1
RETURNING id, owner_id, name, type, lat, lng, hive_count, start_date, end_date, notes, created_at, ledger_hash
`

type UpdateApiaryParams struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Type      ApiaryType     `json:"type"`
	Lat       float64        `json:"lat"`
	Lng       float64        `json:"lng"`
	HiveCount int32          `json:"hive_count"`
	StartDate time.Time      `json:"start_date"`
	EndDate   sql.NullTime   `json:"end_date"`
	Notes     sql.NullString `json:"notes"`
}

func (q *Queries) UpdateApiary(ctx context.Context, arg UpdateApiaryParams) (Apiary, error) {
	row := q.db.QueryRowContext(ctx, updateApiary,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Lat,
		arg.Lng,
		arg.HiveCount,
		arg.StartDate,
		arg.EndDate,
		arg.Notes,
	)
	var i Apiary
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Type,
		&i.Lat,
		&i.Lng,
		&i.HiveCount,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.CreatedAt,
		&i.LedgerHash,
	)
	return i, err
}

const updateApiaryLedgerHash = `-- name: UpdateApiaryLedgerHash :exec
UPDATE apiaries SET ledger_hash = $2 WHERE id = $1
`

type UpdateApiaryLedgerHashParams struct {
	ID         uuid.UUID `json:"id"`
	LedgerHash string    `json:"ledger_hash"`
}

func (q *Queries) UpdateApiaryLedgerHash(ctx context.Context, arg UpdateApiaryLedgerHashParams) error {
	_, err := q.db.ExecContext(ctx, updateApiaryLedgerHash, arg.ID, arg.LedgerHash)
	return err
}
