// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_challenges.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO auth_challenges (id, user_id, method, code_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, method, code_hash, expires_at, verified_at, created_at
`

type CreateChallengeParams struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Method    AuthMethod `json:"method"`
	CodeHash  string     `json:"code_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (AuthChallenge, error) {
	row := q.db.QueryRowContext(ctx, createChallenge,
		arg.ID,
		arg.UserID,
		arg.Method,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Method,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredChallenges = `-- name: DeleteExpiredChallenges :exec
DELETE FROM auth_challenges WHERE expires_at < NOW() AND verified_at IS NULL
`

func (q *Queries) DeleteExpiredChallenges(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredChallenges)
	return err
}

const getChallenge = `-- name: GetChallenge :one
SELECT id, user_id, method, code_hash, expires_at, verified_at, created_at FROM auth_challenges WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChallenge(ctx context.Context, id uuid.UUID) (AuthChallenge, error) {
	row := q.db.QueryRowContext(ctx, getChallenge, id)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Method,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markChallengeVerified = `-- name: MarkChallengeVerified :exec
UPDATE auth_challenges SET verified_at = NOW() WHERE id = $1
`

func (q *Queries) MarkChallengeVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markChallengeVerified, id)
	return err
}
