// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: damage_claims.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

const addDamagePhoto = `-- name: AddDamagePhoto :one
INSERT INTO damage_photos (id, damage_claim_id, url)
VALUES ($1, $2, $3)
RETURNING id, damage_claim_id, url
`

type AddDamagePhotoParams struct {
	ID            uuid.UUID `json:"id"`
	DamageClaimID uuid.UUID `json:"damage_claim_id"`
	Url           string    `json:"url"`
}

func (q *Queries) AddDamagePhoto(ctx context.Context, arg AddDamagePhotoParams) (DamagePhoto, error) {
	row := q.db.QueryRowContext(ctx, addDamagePhoto, arg.ID, arg.DamageClaimID, arg.Url)
	var i DamagePhoto
	err := row.Scan(&i.ID, &i.DamageClaimID, &i.Url)
	return i, err
}

const createDamageClaim = `-- name: CreateDamageClaim :one
INSERT INTO damage_claims (id, beekeeper_id, apiary_id, related_spray_id, description, hive_loss_count, gps_lat, gps_lng, ledger_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, beekeeper_id, apiary_id, related_spray_id, description, hive_loss_count, gps_lat, gps_lng, status, ledger_hash, created_at
`

type CreateDamageClaimParams struct {
	ID             uuid.UUID     `json:"id"`
	BeekeeperID    uuid.UUID     `json:"beekeeper_id"`
	ApiaryID       uuid.UUID     `json:"apiary_id"`
	RelatedSprayID uuid.NullUUID `json:"related_spray_id"`
	Description    string        `json:"description"`
	HiveLossCount  int32         `json:"hive_loss_count"`
	GpsLat         float64       `json:"gps_lat"`
	GpsLng         float64       `json:"gps_lng"`
	LedgerHash     string        `json:"ledger_hash"`
}

func (q *Queries) CreateDamageClaim(ctx context.Context, arg CreateDamageClaimParams) (DamageClaim, error) {
	row := q.db.QueryRowContext(ctx, createDamageClaim,
		arg.ID,
		arg.BeekeeperID,
		arg.ApiaryID,
		arg.RelatedSprayID,
		arg.Description,
		arg.HiveLossCount,
		arg.GpsLat,
		arg.GpsLng,
		arg.LedgerHash,
	)
	var i DamageClaim
	err := row.Scan(
		&i.ID,
		&i.BeekeeperID,
		&i.ApiaryID,
		&i.RelatedSprayID,
		&i.Description,
		&i.HiveLossCount,
		&i.GpsLat,
		&i.GpsLng,
		&i.Status,
		&i.LedgerHash,
		&i.CreatedAt,
	)
	return i, err
}

const getDamageClaim = `-- name: GetDamageClaim :one
SELECT id, beekeeper_id, apiary_id, related_spray_id, description, hive_loss_count, gps_lat, gps_lng, status, ledger_hash, created_at FROM damage_claims WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDamageClaim(ctx context.Context, id uuid.UUID) (DamageClaim, error) {
	row := q.db.QueryRowContext(ctx, getDamageClaim, id)
	var i DamageClaim
	err := row.Scan(
		&i.ID,
		&i.BeekeeperID,
		&i.ApiaryID,
		&i.RelatedSprayID,
		&i.Description,
		&i.HiveLossCount,
		&i.GpsLat,
		&i.GpsLng,
		&i.Status,
		&i.LedgerHash,
		&i.CreatedAt,
	)
	return i, err
}

const listAllDamageClaims = `-- name: ListAllDamageClaims :many
SELECT id, beekeeper_id, apiary_id, related_spray_id, description, hive_loss_count, gps_lat, gps_lng, status, ledger_hash, created_at FROM damage_claims ORDER BY created_at DESC
`

func (q *Queries) ListAllDamageClaims(ctx context.Context) ([]DamageClaim, error) {
	rows, err := q.db.QueryContext(ctx, listAllDamageClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DamageClaim{}
	for rows.Next() {
		var i DamageClaim
		if err := rows.Scan(
			&i.ID,
			&i.BeekeeperID,
			&i.ApiaryID,
			&i.RelatedSprayID,
			&i.Description,
			&i.HiveLossCount,
			&i.GpsLat,
			&i.GpsLng,
			&i.Status,
			&i.LedgerHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDamageClaimsByBeekeeper = `-- name: ListDamageClaimsByBeekeeper :many
SELECT id, beekeeper_id, apiary_id, related_spray_id, description, hive_loss_count, gps_lat, gps_lng, status, ledger_hash, created_at FROM damage_claims WHERE beekeeper_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDamageClaimsByBeekeeper(ctx context.Context, beekeeperID uuid.UUID) ([]DamageClaim, error) {
	rows, err := q.db.QueryContext(ctx, listDamageClaimsByBeekeeper, beekeeperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DamageClaim{}
	for rows.Next() {
		var i DamageClaim
		if err := rows.Scan(
			&i.ID,
			&i.BeekeeperID,
			&i.ApiaryID,
			&i.RelatedSprayID,
			&i.Description,
			&i.HiveLossCount,
			&i.GpsLat,
			&i.GpsLng,
			&i.Status,
			&i.LedgerHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDamagePhotos = `-- name: ListDamagePhotos :many
SELECT id, damage_claim_id, url FROM damage_photos WHERE damage_claim_id = $1
`

func (q *Queries) ListDamagePhotos(ctx context.Context, damageClaimID uuid.UUID) ([]DamagePhoto, error) {
	rows, err := q.db.QueryContext(ctx, listDamagePhotos, damageClaimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DamagePhoto{}
	for rows.Next() {
		var i DamagePhoto
		if err := rows.Scan(&i.ID, &i.DamageClaimID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
