// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger_events.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countLedgerEvents = `-- name: CountLedgerEvents :one
SELECT COUNT(*) FROM ledger_events
`

func (q *Queries) CountLedgerEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLedgerEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLastLedgerEvent = `-- name: GetLastLedgerEvent :one
SELECT id, hash, prev_hash, type, actor_id, payload, created_at FROM ledger_events ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLastLedgerEvent(ctx context.Context) (LedgerEvent, error) {
	row := q.db.QueryRowContext(ctx, getLastLedgerEvent)
	var i LedgerEvent
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.PrevHash,
		&i.Type,
		&i.ActorID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getLedgerEventByHash = `-- name: GetLedgerEventByHash :one
SELECT id, hash, prev_hash, type, actor_id, payload, created_at FROM ledger_events WHERE hash = $1 LIMIT 1
`

func (q *Queries) GetLedgerEventByHash(ctx context.Context, hash string) (LedgerEvent, error) {
	row := q.db.QueryRowContext(ctx, getLedgerEventByHash, hash)
	var i LedgerEvent
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.PrevHash,
		&i.Type,
		&i.ActorID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getNextLedgerEvent = `-- name: GetNextLedgerEvent :one
SELECT id, hash, prev_hash, type, actor_id, payload, created_at FROM ledger_events WHERE prev_hash = $1 LIMIT 1
`

func (q *Queries) GetNextLedgerEvent(ctx context.Context, prevHash sql.NullString) (LedgerEvent, error) {
	row := q.db.QueryRowContext(ctx, getNextLedgerEvent, prevHash)
	var i LedgerEvent
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.PrevHash,
		&i.Type,
		&i.ActorID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const insertLedgerEvent = `-- name: InsertLedgerEvent :one
INSERT INTO ledger_events (id, hash, prev_hash, type, actor_id, payload, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, hash, prev_hash, type, actor_id, payload, created_at
`

type InsertLedgerEventParams struct {
	ID        uuid.UUID       `json:"id"`
	Hash      string          `json:"hash"`
	PrevHash  sql.NullString  `json:"prev_hash"`
	Type      string          `json:"type"`
	ActorID   uuid.NullUUID   `json:"actor_id"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

func (q *Queries) InsertLedgerEvent(ctx context.Context, arg InsertLedgerEventParams) (LedgerEvent, error) {
	row := q.db.QueryRowContext(ctx, insertLedgerEvent,
		arg.ID,
		arg.Hash,
		arg.PrevHash,
		arg.Type,
		arg.ActorID,
		arg.Payload,
		arg.CreatedAt,
	)
	var i LedgerEvent
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.PrevHash,
		&i.Type,
		&i.ActorID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerEventsByActorID = `-- name: ListLedgerEventsByActorID :many
SELECT id, hash, prev_hash, type, actor_id, payload, created_at FROM ledger_events
WHERE actor_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListLedgerEventsByActorID(ctx context.Context, actorID uuid.NullUUID) ([]LedgerEvent, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerEventsByActorID, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEvent{}
	for rows.Next() {
		var i LedgerEvent
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.PrevHash,
			&i.Type,
			&i.ActorID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEventsByApiaryID = `-- name: ListLedgerEventsByApiaryID :many
SELECT id, hash, prev_hash, type, actor_id, payload, created_at FROM ledger_events
WHERE payload->>'apiary_id' = $1::text
ORDER BY created_at ASC
`

func (q *Queries) ListLedgerEventsByApiaryID(ctx context.Context, dollar_1 string) ([]LedgerEvent, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerEventsByApiaryID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEvent{}
	for rows.Next() {
		var i LedgerEvent
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.PrevHash,
			&i.Type,
			&i.ActorID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEventsBySprayID = `-- name: ListLedgerEventsBySprayID :many
SELECT id, hash, prev_hash, type, actor_id, payload, created_at FROM ledger_events
WHERE payload->>'spray_id' = $1::text
ORDER BY created_at ASC
`

func (q *Queries) ListLedgerEventsBySprayID(ctx context.Context, dollar_1 string) ([]LedgerEvent, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerEventsBySprayID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEvent{}
	for rows.Next() {
		var i LedgerEvent
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.PrevHash,
			&i.Type,
			&i.ActorID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEventsByType = `-- name: ListLedgerEventsByType :many
SELECT id, hash, prev_hash, type, actor_id, payload, created_at FROM ledger_events
WHERE ($1::text = '' OR type = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLedgerEventsByTypeParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListLedgerEventsByType(ctx context.Context, arg ListLedgerEventsByTypeParams) ([]LedgerEvent, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerEventsByType, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEvent{}
	for rows.Next() {
		var i LedgerEvent
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.PrevHash,
			&i.Type,
			&i.ActorID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEventsOrdered = `-- name: ListLedgerEventsOrdered :many
SELECT id, hash, prev_hash, type, actor_id, payload, created_at FROM ledger_events ORDER BY created_at ASC
`

func (q *Queries) ListLedgerEventsOrdered(ctx context.Context) ([]LedgerEvent, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerEventsOrdered)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEvent{}
	for rows.Next() {
		var i LedgerEvent
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.PrevHash,
			&i.Type,
			&i.ActorID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEventsPaginated = `-- name: ListLedgerEventsPaginated :many
SELECT id, hash, prev_hash, type, actor_id, payload, created_at FROM ledger_events
WHERE ($1::text = '' OR type = $1)
  AND ($2::uuid IS NULL OR actor_id = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListLedgerEventsPaginatedParams struct {
	Column1 string    `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListLedgerEventsPaginated(ctx context.Context, arg ListLedgerEventsPaginatedParams) ([]LedgerEvent, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerEventsPaginated,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEvent{}
	for rows.Next() {
		var i LedgerEvent
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.PrevHash,
			&i.Type,
			&i.ActorID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
