// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ApiaryType string

const (
	ApiaryTypePermanent ApiaryType = "permanent"
	ApiaryTypePastoral  ApiaryType = "pastoral"
)

func (e *ApiaryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApiaryType(s)
	case string:
		*e = ApiaryType(s)
	default:
		return fmt.Errorf("unsupported scan type for ApiaryType: %T", src)
	}
	return nil
}

type NullApiaryType struct {
	ApiaryType ApiaryType `json:"apiary_type"`
	Valid      bool       `json:"valid"` // Valid is true if ApiaryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApiaryType) Scan(value interface{}) error {
	if value == nil {
		ns.ApiaryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApiaryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApiaryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApiaryType), nil
}

type AuthMethod string

const (
	AuthMethodPush  AuthMethod = "push"
	AuthMethodSms   AuthMethod = "sms"
	AuthMethodEmail AuthMethod = "email"
)

func (e *AuthMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthMethod(s)
	case string:
		*e = AuthMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthMethod: %T", src)
	}
	return nil
}

type NullAuthMethod struct {
	AuthMethod AuthMethod `json:"auth_method"`
	Valid      bool       `json:"valid"` // Valid is true if AuthMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthMethod) Scan(value interface{}) error {
	if value == nil {
		ns.AuthMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthMethod), nil
}

type CallState string

const (
	CallStateSkipped   CallState = "skipped"
	CallStateQueued    CallState = "queued"
	CallStateRinging   CallState = "ringing"
	CallStateAnswered  CallState = "answered"
	CallStateConfirmed CallState = "confirmed"
	CallStateNoInput   CallState = "no_input"
	CallStateNoAnswer  CallState = "no_answer"
	CallStateBusy      CallState = "busy"
	CallStateFailed    CallState = "failed"
	CallStateHungUp    CallState = "hung_up"
)

func (e *CallState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CallState(s)
	case string:
		*e = CallState(s)
	default:
		return fmt.Errorf("unsupported scan type for CallState: %T", src)
	}
	return nil
}

type NullCallState struct {
	CallState CallState `json:"call_state"`
	Valid     bool      `json:"valid"` // Valid is true if CallState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCallState) Scan(value interface{}) error {
	if value == nil {
		ns.CallState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CallState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCallState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CallState), nil
}

type DamageClaimStatus string

const (
	DamageClaimStatusFiled       DamageClaimStatus = "filed"
	DamageClaimStatusUnderReview DamageClaimStatus = "under_review"
	DamageClaimStatusAccepted    DamageClaimStatus = "accepted"
	DamageClaimStatusRejected    DamageClaimStatus = "rejected"
)

func (e *DamageClaimStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DamageClaimStatus(s)
	case string:
		*e = DamageClaimStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DamageClaimStatus: %T", src)
	}
	return nil
}

type NullDamageClaimStatus struct {
	DamageClaimStatus DamageClaimStatus `json:"damage_claim_status"`
	Valid             bool              `json:"valid"` // Valid is true if DamageClaimStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDamageClaimStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DamageClaimStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DamageClaimStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDamageClaimStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DamageClaimStatus), nil
}

type FinalStatus string

const (
	FinalStatusConfirmedCall FinalStatus = "confirmed_call"
	FinalStatusConfirmedSms  FinalStatus = "confirmed_sms"
	FinalStatusConfirmedApp  FinalStatus = "confirmed_app"
	FinalStatusUnconfirmed   FinalStatus = "unconfirmed"
	FinalStatusFailed        FinalStatus = "failed"
)

func (e *FinalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FinalStatus(s)
	case string:
		*e = FinalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FinalStatus: %T", src)
	}
	return nil
}

type NullFinalStatus struct {
	FinalStatus FinalStatus `json:"final_status"`
	Valid       bool        `json:"valid"` // Valid is true if FinalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFinalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FinalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FinalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFinalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FinalStatus), nil
}

type InAppAction string

const (
	InAppActionMoveHives   InAppAction = "move_hives"
	InAppActionSealInPlace InAppAction = "seal_in_place"
)

func (e *InAppAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InAppAction(s)
	case string:
		*e = InAppAction(s)
	default:
		return fmt.Errorf("unsupported scan type for InAppAction: %T", src)
	}
	return nil
}

type NullInAppAction struct {
	InAppAction InAppAction `json:"in_app_action"`
	Valid       bool        `json:"valid"` // Valid is true if InAppAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInAppAction) Scan(value interface{}) error {
	if value == nil {
		ns.InAppAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InAppAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInAppAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InAppAction), nil
}

type PushState string

const (
	PushStatePending   PushState = "pending"
	PushStateSent      PushState = "sent"
	PushStateDelivered PushState = "delivered"
	PushStateOpened    PushState = "opened"
)

func (e *PushState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PushState(s)
	case string:
		*e = PushState(s)
	default:
		return fmt.Errorf("unsupported scan type for PushState: %T", src)
	}
	return nil
}

type NullPushState struct {
	PushState PushState `json:"push_state"`
	Valid     bool      `json:"valid"` // Valid is true if PushState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPushState) Scan(value interface{}) error {
	if value == nil {
		ns.PushState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PushState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPushState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PushState), nil
}

type SmsState string

const (
	SmsStateSkipped   SmsState = "skipped"
	SmsStateQueued    SmsState = "queued"
	SmsStateSent      SmsState = "sent"
	SmsStateDelivered SmsState = "delivered"
	SmsStateConfirmed SmsState = "confirmed"
	SmsStateNoReply   SmsState = "no_reply"
	SmsStateFailed    SmsState = "failed"
)

func (e *SmsState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SmsState(s)
	case string:
		*e = SmsState(s)
	default:
		return fmt.Errorf("unsupported scan type for SmsState: %T", src)
	}
	return nil
}

type NullSmsState struct {
	SmsState SmsState `json:"sms_state"`
	Valid    bool     `json:"valid"` // Valid is true if SmsState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSmsState) Scan(value interface{}) error {
	if value == nil {
		ns.SmsState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SmsState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSmsState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SmsState), nil
}

type SprayStatus string

const (
	SprayStatusScheduled  SprayStatus = "scheduled"
	SprayStatusInProgress SprayStatus = "in_progress"
	SprayStatusCompleted  SprayStatus = "completed"
	SprayStatusCancelled  SprayStatus = "cancelled"
)

func (e *SprayStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SprayStatus(s)
	case string:
		*e = SprayStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SprayStatus: %T", src)
	}
	return nil
}

type NullSprayStatus struct {
	SprayStatus SprayStatus `json:"spray_status"`
	Valid       bool        `json:"valid"` // Valid is true if SprayStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSprayStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SprayStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SprayStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSprayStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SprayStatus), nil
}

type UserRole string

const (
	UserRoleApicultor UserRole = "apicultor"
	UserRoleFermier   UserRole = "fermier"
	UserRoleInspector UserRole = "inspector"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AlertDispatch struct {
	ID               uuid.UUID       `json:"id"`
	SprayReportID    uuid.UUID       `json:"spray_report_id"`
	BeekeeperID      uuid.UUID       `json:"beekeeper_id"`
	ApiaryID         uuid.UUID       `json:"apiary_id"`
	DistanceM        float64         `json:"distance_m"`
	Downwind         bool            `json:"downwind"`
	PushState        PushState       `json:"push_state"`
	PushAt           sql.NullTime    `json:"push_at"`
	CallState        CallState       `json:"call_state"`
	CallAt           sql.NullTime    `json:"call_at"`
	CallAttempts     int32           `json:"call_attempts"`
	SmsState         SmsState        `json:"sms_state"`
	SmsAt            sql.NullTime    `json:"sms_at"`
	InAppConfirmedAt sql.NullTime    `json:"in_app_confirmed_at"`
	InAppAction      NullInAppAction `json:"in_app_action"`
	FinalStatus      NullFinalStatus `json:"final_status"`
	TwilioCallSid    sql.NullString  `json:"twilio_call_sid"`
	TwilioSmsSid     sql.NullString  `json:"twilio_sms_sid"`
	LedgerHash       string          `json:"ledger_hash"`
	CreatedAt        time.Time       `json:"created_at"`
}

type Apiary struct {
	ID         uuid.UUID      `json:"id"`
	OwnerID    uuid.UUID      `json:"owner_id"`
	Name       string         `json:"name"`
	Type       ApiaryType     `json:"type"`
	Lat        float64        `json:"lat"`
	Lng        float64        `json:"lng"`
	HiveCount  int32          `json:"hive_count"`
	StartDate  time.Time      `json:"start_date"`
	EndDate    sql.NullTime   `json:"end_date"`
	Notes      sql.NullString `json:"notes"`
	CreatedAt  time.Time      `json:"created_at"`
	LedgerHash string         `json:"ledger_hash"`
}

type AuthChallenge struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	Method     AuthMethod   `json:"method"`
	CodeHash   string       `json:"code_hash"`
	ExpiresAt  time.Time    `json:"expires_at"`
	VerifiedAt sql.NullTime `json:"verified_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

type DamageClaim struct {
	ID             uuid.UUID         `json:"id"`
	BeekeeperID    uuid.UUID         `json:"beekeeper_id"`
	ApiaryID       uuid.UUID         `json:"apiary_id"`
	RelatedSprayID uuid.NullUUID     `json:"related_spray_id"`
	Description    string            `json:"description"`
	HiveLossCount  int32             `json:"hive_loss_count"`
	GpsLat         float64           `json:"gps_lat"`
	GpsLng         float64           `json:"gps_lng"`
	Status         DamageClaimStatus `json:"status"`
	LedgerHash     string            `json:"ledger_hash"`
	CreatedAt      time.Time         `json:"created_at"`
}

type DamagePhoto struct {
	ID            uuid.UUID `json:"id"`
	DamageClaimID uuid.UUID `json:"damage_claim_id"`
	Url           string    `json:"url"`
}

type LedgerEvent struct {
	ID        uuid.UUID       `json:"id"`
	Hash      string          `json:"hash"`
	PrevHash  sql.NullString  `json:"prev_hash"`
	Type      string          `json:"type"`
	ActorID   uuid.NullUUID   `json:"actor_id"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

type Parcel struct {
	ID              uuid.UUID      `json:"id"`
	OwnerID         uuid.UUID      `json:"owner_id"`
	Name            string         `json:"name"`
	CadastralNumber string         `json:"cadastral_number"`
	Lat             float64        `json:"lat"`
	Lng             float64        `json:"lng"`
	SurfaceHa       float64        `json:"surface_ha"`
	DefaultCrop     sql.NullString `json:"default_crop"`
	County          string         `json:"county"`
	Locality        string         `json:"locality"`
}

type PushSubscription struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Endpoint  string    `json:"endpoint"`
	P256dh    string    `json:"p256dh"`
	Auth      string    `json:"auth"`
	CreatedAt time.Time `json:"created_at"`
}

type SprayReport struct {
	ID                    uuid.UUID             `json:"id"`
	FarmerID              uuid.UUID             `json:"farmer_id"`
	ParcelID              uuid.UUID             `json:"parcel_id"`
	Crop                  string                `json:"crop"`
	Substance             string                `json:"substance"`
	Toxicity              string                `json:"toxicity"`
	SurfaceHa             float64               `json:"surface_ha"`
	ScheduledAt           time.Time             `json:"scheduled_at"`
	DurationHours         float64               `json:"duration_hours"`
	Notes                 sql.NullString        `json:"notes"`
	Status                SprayStatus           `json:"status"`
	AffectedApiariesCount int32                 `json:"affected_apiaries_count"`
	LedgerHash            string                `json:"ledger_hash"`
	CreatedAt             time.Time             `json:"created_at"`
	DoseKgHa              float64               `json:"dose_kg_ha"`
	AiRiskScore           sql.NullFloat64       `json:"ai_risk_score"`
	AiRiskLevel           sql.NullString        `json:"ai_risk_level"`
	AiExplanationRo       sql.NullString        `json:"ai_explanation_ro"`
	AiRecommendedAction   sql.NullString        `json:"ai_recommended_action"`
	AiWarnings            pqtype.NullRawMessage `json:"ai_warnings"`
	AiZones               pqtype.NullRawMessage `json:"ai_zones"`
}

type Substance struct {
	ID       uuid.UUID `json:"id"`
	Label    string    `json:"label"`
	Toxicity string    `json:"toxicity"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Cnp          string    `json:"cnp"`
	FullName     string    `json:"full_name"`
	Email        string    `json:"email"`
	Phone        string    `json:"phone"`
	Role         UserRole  `json:"role"`
	County       string    `json:"county"`
	Locality     string    `json:"locality"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
