// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parcels.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createParcel = `-- name: CreateParcel :one
INSERT INTO parcels (id, owner_id, name, cadastral_number, lat, lng, surface_ha, default_crop, county, locality)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, owner_id, name, cadastral_number, lat, lng, surface_ha, default_crop, county, locality
`

type CreateParcelParams struct {
	ID              uuid.UUID      `json:"id"`
	OwnerID         uuid.UUID      `json:"owner_id"`
	Name            string         `json:"name"`
	CadastralNumber string         `json:"cadastral_number"`
	Lat             float64        `json:"lat"`
	Lng             float64        `json:"lng"`
	SurfaceHa       float64        `json:"surface_ha"`
	DefaultCrop     sql.NullString `json:"default_crop"`
	County          string         `json:"county"`
	Locality        string         `json:"locality"`
}

func (q *Queries) CreateParcel(ctx context.Context, arg CreateParcelParams) (Parcel, error) {
	row := q.db.QueryRowContext(ctx, createParcel,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.CadastralNumber,
		arg.Lat,
		arg.Lng,
		arg.SurfaceHa,
		arg.DefaultCrop,
		arg.County,
		arg.Locality,
	)
	var i Parcel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CadastralNumber,
		&i.Lat,
		&i.Lng,
		&i.SurfaceHa,
		&i.DefaultCrop,
		&i.County,
		&i.Locality,
	)
	return i, err
}

const getParcel = `-- name: GetParcel :one
SELECT id, owner_id, name, cadastral_number, lat, lng, surface_ha, default_crop, county, locality FROM parcels WHERE id = $1 LIMIT 1
`

func (q *Queries) GetParcel(ctx context.Context, id uuid.UUID) (Parcel, error) {
	row := q.db.QueryRowContext(ctx, getParcel, id)
	var i Parcel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CadastralNumber,
		&i.Lat,
		&i.Lng,
		&i.SurfaceHa,
		&i.DefaultCrop,
		&i.County,
		&i.Locality,
	)
	return i, err
}

const listParcelsByOwner = `-- name: ListParcelsByOwner :many
SELECT id, owner_id, name, cadastral_number, lat, lng, surface_ha, default_crop, county, locality FROM parcels WHERE owner_id = $1 ORDER BY name
`

func (q *Queries) ListParcelsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Parcel, error) {
	rows, err := q.db.QueryContext(ctx, listParcelsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Parcel{}
	for rows.Next() {
		var i Parcel
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CadastralNumber,
			&i.Lat,
			&i.Lng,
			&i.SurfaceHa,
			&i.DefaultCrop,
			&i.County,
			&i.Locality,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
