// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_subscriptions.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPushSubscription = `-- name: CreatePushSubscription :one
INSERT INTO push_subscriptions (id, user_id, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (endpoint) DO UPDATE
    SET p256dh = EXCLUDED.p256dh, auth = EXCLUDED.auth, user_id = EXCLUDED.user_id
RETURNING id, user_id, endpoint, p256dh, auth, created_at
`

type CreatePushSubscriptionParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	Endpoint string    `json:"endpoint"`
	P256dh   string    `json:"p256dh"`
	Auth     string    `json:"auth"`
}

func (q *Queries) CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRowContext(ctx, createPushSubscription,
		arg.ID,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.CreatedAt,
	)
	return i, err
}

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions WHERE id = $1 AND user_id = $2
`

type DeletePushSubscriptionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deletePushSubscription, arg.ID, arg.UserID)
	return err
}

const getPushSubscription = `-- name: GetPushSubscription :one
SELECT id, user_id, endpoint, p256dh, auth, created_at FROM push_subscriptions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPushSubscription(ctx context.Context, id uuid.UUID) (PushSubscription, error) {
	row := q.db.QueryRowContext(ctx, getPushSubscription, id)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.CreatedAt,
	)
	return i, err
}

const listPushSubscriptionsByUser = `-- name: ListPushSubscriptionsByUser :many
SELECT id, user_id, endpoint, p256dh, auth, created_at FROM push_subscriptions WHERE user_id = $1
`

func (q *Queries) ListPushSubscriptionsByUser(ctx context.Context, userID uuid.UUID) ([]PushSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listPushSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
