// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spray_reports.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createSprayReport = `-- name: CreateSprayReport :one
INSERT INTO spray_reports (id, farmer_id, parcel_id, crop, substance, toxicity, surface_ha, dose_kg_ha, scheduled_at, duration_hours, notes, ledger_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, farmer_id, parcel_id, crop, substance, toxicity, surface_ha, scheduled_at, duration_hours, notes, status, affected_apiaries_count, ledger_hash, created_at, dose_kg_ha, ai_risk_score, ai_risk_level, ai_explanation_ro, ai_recommended_action, ai_warnings, ai_zones
`

type CreateSprayReportParams struct {
	ID            uuid.UUID      `json:"id"`
	FarmerID      uuid.UUID      `json:"farmer_id"`
	ParcelID      uuid.UUID      `json:"parcel_id"`
	Crop          string         `json:"crop"`
	Substance     string         `json:"substance"`
	Toxicity      string         `json:"toxicity"`
	SurfaceHa     float64        `json:"surface_ha"`
	DoseKgHa      float64        `json:"dose_kg_ha"`
	ScheduledAt   time.Time      `json:"scheduled_at"`
	DurationHours float64        `json:"duration_hours"`
	Notes         sql.NullString `json:"notes"`
	LedgerHash    string         `json:"ledger_hash"`
}

func (q *Queries) CreateSprayReport(ctx context.Context, arg CreateSprayReportParams) (SprayReport, error) {
	row := q.db.QueryRowContext(ctx, createSprayReport,
		arg.ID,
		arg.FarmerID,
		arg.ParcelID,
		arg.Crop,
		arg.Substance,
		arg.Toxicity,
		arg.SurfaceHa,
		arg.DoseKgHa,
		arg.ScheduledAt,
		arg.DurationHours,
		arg.Notes,
		arg.LedgerHash,
	)
	var i SprayReport
	err := row.Scan(
		&i.ID,
		&i.FarmerID,
		&i.ParcelID,
		&i.Crop,
		&i.Substance,
		&i.Toxicity,
		&i.SurfaceHa,
		&i.ScheduledAt,
		&i.DurationHours,
		&i.Notes,
		&i.Status,
		&i.AffectedApiariesCount,
		&i.LedgerHash,
		&i.CreatedAt,
		&i.DoseKgHa,
		&i.AiRiskScore,
		&i.AiRiskLevel,
		&i.AiExplanationRo,
		&i.AiRecommendedAction,
		&i.AiWarnings,
		&i.AiZones,
	)
	return i, err
}

const getSprayReport = `-- name: GetSprayReport :one
SELECT id, farmer_id, parcel_id, crop, substance, toxicity, surface_ha, scheduled_at, duration_hours, notes, status, affected_apiaries_count, ledger_hash, created_at, dose_kg_ha, ai_risk_score, ai_risk_level, ai_explanation_ro, ai_recommended_action, ai_warnings, ai_zones FROM spray_reports WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSprayReport(ctx context.Context, id uuid.UUID) (SprayReport, error) {
	row := q.db.QueryRowContext(ctx, getSprayReport, id)
	var i SprayReport
	err := row.Scan(
		&i.ID,
		&i.FarmerID,
		&i.ParcelID,
		&i.Crop,
		&i.Substance,
		&i.Toxicity,
		&i.SurfaceHa,
		&i.ScheduledAt,
		&i.DurationHours,
		&i.Notes,
		&i.Status,
		&i.AffectedApiariesCount,
		&i.LedgerHash,
		&i.CreatedAt,
		&i.DoseKgHa,
		&i.AiRiskScore,
		&i.AiRiskLevel,
		&i.AiExplanationRo,
		&i.AiRecommendedAction,
		&i.AiWarnings,
		&i.AiZones,
	)
	return i, err
}

const listActiveSprayReports = `-- name: ListActiveSprayReports :many
SELECT id, farmer_id, parcel_id, crop, substance, toxicity, surface_ha, scheduled_at, duration_hours, notes, status, affected_apiaries_count, ledger_hash, created_at, dose_kg_ha, ai_risk_score, ai_risk_level, ai_explanation_ro, ai_recommended_action, ai_warnings, ai_zones FROM spray_reports WHERE status IN ('scheduled', 'in_progress') ORDER BY scheduled_at
`

func (q *Queries) ListActiveSprayReports(ctx context.Context) ([]SprayReport, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSprayReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprayReport{}
	for rows.Next() {
		var i SprayReport
		if err := rows.Scan(
			&i.ID,
			&i.FarmerID,
			&i.ParcelID,
			&i.Crop,
			&i.Substance,
			&i.Toxicity,
			&i.SurfaceHa,
			&i.ScheduledAt,
			&i.DurationHours,
			&i.Notes,
			&i.Status,
			&i.AffectedApiariesCount,
			&i.LedgerHash,
			&i.CreatedAt,
			&i.DoseKgHa,
			&i.AiRiskScore,
			&i.AiRiskLevel,
			&i.AiExplanationRo,
			&i.AiRecommendedAction,
			&i.AiWarnings,
			&i.AiZones,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSprayReports = `-- name: ListAllSprayReports :many
SELECT id, farmer_id, parcel_id, crop, substance, toxicity, surface_ha, scheduled_at, duration_hours, notes, status, affected_apiaries_count, ledger_hash, created_at, dose_kg_ha, ai_risk_score, ai_risk_level, ai_explanation_ro, ai_recommended_action, ai_warnings, ai_zones FROM spray_reports ORDER BY created_at DESC
`

func (q *Queries) ListAllSprayReports(ctx context.Context) ([]SprayReport, error) {
	rows, err := q.db.QueryContext(ctx, listAllSprayReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprayReport{}
	for rows.Next() {
		var i SprayReport
		if err := rows.Scan(
			&i.ID,
			&i.FarmerID,
			&i.ParcelID,
			&i.Crop,
			&i.Substance,
			&i.Toxicity,
			&i.SurfaceHa,
			&i.ScheduledAt,
			&i.DurationHours,
			&i.Notes,
			&i.Status,
			&i.AffectedApiariesCount,
			&i.LedgerHash,
			&i.CreatedAt,
			&i.DoseKgHa,
			&i.AiRiskScore,
			&i.AiRiskLevel,
			&i.AiExplanationRo,
			&i.AiRecommendedAction,
			&i.AiWarnings,
			&i.AiZones,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprayReportsByFarmer = `-- name: ListSprayReportsByFarmer :many
SELECT id, farmer_id, parcel_id, crop, substance, toxicity, surface_ha, scheduled_at, duration_hours, notes, status, affected_apiaries_count, ledger_hash, created_at, dose_kg_ha, ai_risk_score, ai_risk_level, ai_explanation_ro, ai_recommended_action, ai_warnings, ai_zones FROM spray_reports WHERE farmer_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSprayReportsByFarmer(ctx context.Context, farmerID uuid.UUID) ([]SprayReport, error) {
	rows, err := q.db.QueryContext(ctx, listSprayReportsByFarmer, farmerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SprayReport{}
	for rows.Next() {
		var i SprayReport
		if err := rows.Scan(
			&i.ID,
			&i.FarmerID,
			&i.ParcelID,
			&i.Crop,
			&i.Substance,
			&i.Toxicity,
			&i.SurfaceHa,
			&i.ScheduledAt,
			&i.DurationHours,
			&i.Notes,
			&i.Status,
			&i.AffectedApiariesCount,
			&i.LedgerHash,
			&i.CreatedAt,
			&i.DoseKgHa,
			&i.AiRiskScore,
			&i.AiRiskLevel,
			&i.AiExplanationRo,
			&i.AiRecommendedAction,
			&i.AiWarnings,
			&i.AiZones,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSprayAIAssessment = `-- name: UpdateSprayAIAssessment :exec
UPDATE spray_reports SET
    ai_risk_score         = $2,
    ai_risk_level         = $3,
    ai_explanation_ro     = $4,
    ai_recommended_action = $5,
    ai_warnings           = $6,
    ai_zones              = $7
WHERE id = $1
`

type UpdateSprayAIAssessmentParams struct {
	ID                  uuid.UUID             `json:"id"`
	AiRiskScore         sql.NullFloat64       `json:"ai_risk_score"`
	AiRiskLevel         sql.NullString        `json:"ai_risk_level"`
	AiExplanationRo     sql.NullString        `json:"ai_explanation_ro"`
	AiRecommendedAction sql.NullString        `json:"ai_recommended_action"`
	AiWarnings          pqtype.NullRawMessage `json:"ai_warnings"`
	AiZones             pqtype.NullRawMessage `json:"ai_zones"`
}

func (q *Queries) UpdateSprayAIAssessment(ctx context.Context, arg UpdateSprayAIAssessmentParams) error {
	_, err := q.db.ExecContext(ctx, updateSprayAIAssessment,
		arg.ID,
		arg.AiRiskScore,
		arg.AiRiskLevel,
		arg.AiExplanationRo,
		arg.AiRecommendedAction,
		arg.AiWarnings,
		arg.AiZones,
	)
	return err
}

const updateSprayReportAffectedCount = `-- name: UpdateSprayReportAffectedCount :exec
UPDATE spray_reports SET affected_apiaries_count = $2 WHERE id = $1
`

type UpdateSprayReportAffectedCountParams struct {
	ID                    uuid.UUID `json:"id"`
	AffectedApiariesCount int32     `json:"affected_apiaries_count"`
}

func (q *Queries) UpdateSprayReportAffectedCount(ctx context.Context, arg UpdateSprayReportAffectedCountParams) error {
	_, err := q.db.ExecContext(ctx, updateSprayReportAffectedCount, arg.ID, arg.AffectedApiariesCount)
	return err
}

const updateSprayReportLedgerHash = `-- name: UpdateSprayReportLedgerHash :exec
UPDATE spray_reports SET ledger_hash = $2 WHERE id = $1
`

type UpdateSprayReportLedgerHashParams struct {
	ID         uuid.UUID `json:"id"`
	LedgerHash string    `json:"ledger_hash"`
}

func (q *Queries) UpdateSprayReportLedgerHash(ctx context.Context, arg UpdateSprayReportLedgerHashParams) error {
	_, err := q.db.ExecContext(ctx, updateSprayReportLedgerHash, arg.ID, arg.LedgerHash)
	return err
}

const updateSprayReportStatus = `-- name: UpdateSprayReportStatus :exec
UPDATE spray_reports SET status = $2 WHERE id = $1
`

type UpdateSprayReportStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status SprayStatus `json:"status"`
}

func (q *Queries) UpdateSprayReportStatus(ctx context.Context, arg UpdateSprayReportStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSprayReportStatus, arg.ID, arg.Status)
	return err
}
