// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: substances.sql

package dbsqlc

import (
	"context"
)

const getSubstanceByLabel = `-- name: GetSubstanceByLabel :one
SELECT id, label, toxicity FROM substances WHERE label = $1 LIMIT 1
`

func (q *Queries) GetSubstanceByLabel(ctx context.Context, label string) (Substance, error) {
	row := q.db.QueryRowContext(ctx, getSubstanceByLabel, label)
	var i Substance
	err := row.Scan(&i.ID, &i.Label, &i.Toxicity)
	return i, err
}

const listSubstances = `-- name: ListSubstances :many
SELECT id, label, toxicity FROM substances ORDER BY label
`

func (q *Queries) ListSubstances(ctx context.Context) ([]Substance, error) {
	rows, err := q.db.QueryContext(ctx, listSubstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Substance{}
	for rows.Next() {
		var i Substance
		if err := rows.Scan(&i.ID, &i.Label, &i.Toxicity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
