// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, cnp, full_name, email, phone, role, county, locality, password_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, cnp, full_name, email, phone, role, county, locality, password_hash, created_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Cnp          string    `json:"cnp"`
	FullName     string    `json:"full_name"`
	Email        string    `json:"email"`
	Phone        string    `json:"phone"`
	Role         UserRole  `json:"role"`
	County       string    `json:"county"`
	Locality     string    `json:"locality"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Cnp,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Role,
		arg.County,
		arg.Locality,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Cnp,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.County,
		&i.Locality,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByCNP = `-- name: GetUserByCNP :one
SELECT id, cnp, full_name, email, phone, role, county, locality, password_hash, created_at FROM users WHERE cnp = $1 LIMIT 1
`

func (q *Queries) GetUserByCNP(ctx context.Context, cnp string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByCNP, cnp)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Cnp,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.County,
		&i.Locality,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, cnp, full_name, email, phone, role, county, locality, password_hash, created_at FROM users WHERE LOWER(email) = LOWER($1) LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Cnp,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.County,
		&i.Locality,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, cnp, full_name, email, phone, role, county, locality, password_hash, created_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Cnp,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.County,
		&i.Locality,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, cnp, full_name, email, phone, role, county, locality, password_hash, created_at FROM users ORDER BY full_name
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Cnp,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.County,
			&i.Locality,
			&i.PasswordHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT id, cnp, full_name, email, phone, role, county, locality, password_hash, created_at FROM users WHERE role = $1 ORDER BY full_name
`

func (q *Queries) ListUsersByRole(ctx context.Context, role UserRole) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Cnp,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.County,
			&i.Locality,
			&i.PasswordHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
